# Generated by Django 3.1.2 on 2020-10-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensesandcertifications',
            name='Credential_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='licensesandcertifications',
            name='expiration_date',
            field=models.DateField(blank=True),
        ),
    ]
