# Generated by Django 3.1.2 on 2020-10-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20201014_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensesandcertifications',
            name='Credential_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='licensesandcertifications',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
