# Generated by Django 3.1.2 on 2020-10-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20201014_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='final_gpa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
